#ifndef DFC_CONSTANTS_H
#define DFC_CONSTANTS_H

#define TOO_MANY_ENTRIES_IN_SMALL_CT_EXIT_CODE 2
#define TOO_MANY_PID_IN_SMALL_CT_EXIT_CODE 3
#define TOO_MANY_ENTRIES_IN_LARGE_CT_EXIT_CODE 4
#define TOO_MANY_PID_IN_LARGE_CT_EXIT_CODE 5
#define PATTERN_TOO_LARGE_EXIT_CODE 6
#define TOO_MANY_EQUAL_PATTERNS_EXIT_CODE 7
#define OPENCL_NO_PLATFORM_EXIT_CODE 8
#define OPENCL_NO_DEVICE_EXIT_CODE 9
#define OPENCL_COULD_NOT_CREATE_CONTEXT 10
#define COULD_NOT_LOAD_KERNEL 11
#define OPENCL_COULD_NOT_CREATE_PROGRAM 12
#define OPENCL_COULD_NOT_BUILD_PROGRAM 13
#define OPENCL_COULD_NOT_CREATE_KERNEL 14
#define OPENCL_COULD_NOT_START_KERNEL 15
#define OPENCL_COULD_NOT_READ_RESULTS 16

#endif